### ISSUE TITLE
version not found

### ISSUE THREAD

**Issue by rafaltrojanowski** [danielspaniel/ember-data-factory-guy#102]
I'm trying install specific version for my ember-data and after running this command

$ ember install ember-data-factory-guy@1.1.2

I got:
version not found: ember-data-factory-guy@1.1.2

`
Error: version not found: ember-data-factory-guy@1.1.2
  at setData (/Users/u/Projects/iRonin/time_tracking/web-app-ember/node_modules/ember-cli/node_modules/npm/lib/cache/add-named.js:137:12)
  at RES (/Users/u/Projects/iRonin/time_tracking/web-app-ember/node_modules/ember-cli/node_modules/npm/node_modules/inflight/inflight.js:23:14)
  at f (/Users/u/Projects/iRonin/time_tracking/web-app-ember/node_modules/ember-cli/node_modules/npm/node_modules/once/once.js:17:25)
  at fixName (/Users/u/Projects/iRonin/time_tracking/web-app-ember/node_modules/ember-cli/node_modules/npm/lib/cache/add-named.js:29:5)
  at saved (/Users/u/Projects/iRonin/time_tracking/web-app-ember/node_modules/ember-cli/node_modules/npm/lib/cache/caching-client.js:173:7)
  at FSReqWrap.oncomplete (fs.js:95:15)
`

Is it possible to install 1.1.2 or should I update ember-data?

**Comment by danielspaniel** [comment]
Arghh .. I forgot to publish that @rafaltrojanowski .. keep forgetting to npm publish after I make a new version. Anyway .. just did that .. so thanks for the reminder :)
