### ISSUE TITLE
Could not find module `active-model-adapter` 

### ISSUE THREAD

**Issue by mminkoff** [danielspaniel/ember-data-factory-guy#120]
I tried upgrading to 1.13.6 but now my tests fail.  I'm on Ember 1.13.7, ED 1.13.8, and Ember-cli 1.13.8.

Here's what I'm seeing: 

```Died on test #1     at Object.TestLoader.moduleLoadFailure (http://localhost:4200/assets/test-support.js:6638:11)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:31:14)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:4200/assets/test-loader.js:40:24)
    at http://localhost:4200/assets/test-support.js:6647:16: Could not find module `active-model-adapter` imported from `ember-data-factory-guy/factory-guy`@ 1 ms
Source: 	
Error: Could not find module `active-model-adapter` imported from `ember-data-factory-guy/factory-guy`
    at requireFrom (http://localhost:4200/assets/vendor.js:119:13)
    at reify (http://localhost:4200/assets/vendor.js:106:22)
    at mod.state (http://localhost:4200/assets/vendor.js:149:17)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at requireFrom (http://localhost:4200/assets/vendor.js:121:12)
    at reify (http://localhost:4200/assets/vendor.js:106:22)
    at mod.state (http://localhost:4200/assets/vendor.js:149:17)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)```

**Comment by visoft** [comment]
I'm seeing the same thing running 1.13.6, with Ember 1.13.7 and ED 1.13.8

**Comment by kostyl** [comment]
same here

**Comment by danielspaniel** [comment]
hmm .. yeah .. that is a bummer .. I think what happened was in v1.3.6 ( which was created from merged PR ) the active-model-adapter was included in package.json ( of ember-data-factory-guy) so it's not really imported by npm when you install factory guy, which means I kind of messed that up.
 Give me a few days to work that out and use v1.3.5 till I get that sorted out.

**Comment by mminkoff** [comment]
Absolutely!  Thanks for your amazing and super-helpful work!

**Comment by danielspaniel** [comment]
@mminkoff, can you try v1.3.7 and see if this fixes the issue for you. I think it does, but want to verify.

**Comment by mminkoff** [comment]
looks all clear here @danielspaniel - thanks!
