### ISSUE TITLE
Make throws a registry.resolve error

### ISSUE THREAD

**Issue by ajsridha** [danielspaniel/ember-data-factory-guy#218]
When I try to do: `make('user', {status: 'active'});`
```
Source: 	
TypeError: registry.resolve is not a function
    at Class._modelForMixin (http://localhost:4200/assets/vendor.js:134911:30)
    at Class.modelFor (http://localhost:4200/assets/vendor.js:134939:26)
    at _default.extractAttributes (http://localhost:4200/assets/vendor.js:235997:20)
    at _default.convertSingle (http://localhost:4200/assets/vendor.js:236255:31)
    at _default.convert (http://localhost:4200/assets/vendor.js:235914:23)
    at _default.convertForBuild (http://localhost:4200/assets/vendor.js:235578:30)
    at FactoryGuy.build (http://localhost:4200/assets/vendor.js:237316:36)
    at Object.<anonymous> (http://localhost:4200/assets/tests.js:22029:36)
    at Object.wrapper (http://localhost:4200/assets/test-support.js:6632:29)
    at runTest (http://localhost:4200/assets/test-support.js:2796:28)
```

I know it can find `factories/user.js` correctly. Any ideas why this error appears?

**Comment by danielspaniel** [comment]
does your application work fine in development? 
 can you give me access to your repo so I can see what is happening? 
  Otherwise I can't help too much because this looks like something really whacky is happening ( in your models .. not factories )

**Comment by ajsridha** [comment]
It does work find in development. However I can't easily give you access to the repo. But thanks for your idea about the problem existing in the model. I will close this issue. Thanks!
