### ISSUE TITLE
SyntaxError: ember-data-factory-guy/scenario.js: Unexpected token (6:21)

### ISSUE THREAD

**Issue by jakeonfire** [danielspaniel/ember-data-factory-guy#278]
since upgrading to 2.12.1 building my app raises an error:
```
File: ember-data-factory-guy/scenario.js
The Broccoli Plugin: [Babel] failed with:
SyntaxError: ember-data-factory-guy/scenario.js: Unexpected token (6:21)

import Ember from 'ember';
import FactoryGuy, { * as fgMethods } from 'ember-data-factory-guy';

var proxyFx = ['make', 'makeNew', 'makeList', 'build', 'buildList', 'mockFind', 'mockFindRecord', 'mockFindAll', 'mockReload', 'mockQuery', 'mockQueryRecord', 'mockUpdate', 'mockCreate', 'mockDelete'];

    at Parser.pp.raise (/Users/jacob.frautschi/workspace/orange/dashboard/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/jacob.frautschi/workspace/orange/dashboard/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseIdent (/Users/jacob.frautschi/workspace/orange/dashboard/node_modules/babylon/lib/parser/expression.js:818:10)
    at Parser.pp.parseImportSpecifiers (/Users/jacob.frautschi/workspace/orange/dashboard/node_modules/babylon/lib/parser/statement.js:836:31)
    at Parser.parseImportSpecifiers (/Users/jacob.frautschi/workspace/orange/dashboard/node_modules/babylon/lib/plugins/flow.js:926:13)
    at Parser.pp.parseImport (/Users/jacob.frautschi/workspace/orange/dashboard/node_modules/babylon/lib/parser/statement.js:796:10)
    at Parser.pp.parseStatement (/Users/jacob.frautschi/workspace/orange/dashboard/node_modules/babylon/lib/parser/statement.js:115:65)
```

so something to do with the import statement? doesn't happen with 2.12.0.

**Comment by danielspaniel** [comment]
interesting .. I just moved the ember-cli-babel package and moved it to dependencies, so something about the new babel package or ?? 
let me try it out and see what is the problem ... unless you can fix it first?

**Comment by jakeonfire** [comment]
sorry, no time today...

**Comment by jakeonfire** [comment]
i do think import * only works in the outer context... destructuring assignments and a wildcard feels weird, but can't confirm.

**Comment by jakeonfire** [comment]
see the second-to-last example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by danielspaniel** [comment]
seems like I should be able to to this then .. what looks off?
import FactoryGuy, * as fgMethods from 'ember-data-factory-guy';since the docs are saying =>import defaultMember, * as name from "module-name"; 

    On Wednesday, March 22, 2017 6:37 PM, Jacob Frautschi <notifications@github.com> wrote:
 

 see the second-to-last example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import—

**Comment by jakeonfire** [comment]
oh weird... the `scenario.js` source is different from that printed in the error. how is that the case? is it some intermediary, transpiled version?

**Comment by jakeonfire** [comment]
i can tell you that with my project
 - npm install ember-data-factory-guy 2.12.0, ember build ✅ 
 - npm install ember-data-factory-guy 2.12.1, ember build 🚫

**Comment by danielspaniel** [comment]
fixed 
https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.12.2
thanks for bringing this up .. really whacky
