### ISSUE TITLE
Install is not working

### ISSUE THREAD

**Issue by pixelterra** [danielspaniel/ember-data-factory-guy#72]
$ ember install:addon ember-data-factory-guy
version: 0.2.1

A new version of ember-cli is available (0.2.3). To install it, type ember update.
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /home/blieb/projects/akita/frontend/node_modules/ember-cli/lib/models/project.js:459:53
    at find (/home/blieb/projects/akita/frontend/node_modules/ember-cli/node_modules/lodash-node/modern/collections/find.js:64:11)
    at Project.findAddonByName (/home/blieb/projects/akita/frontend/node_modules/ember-cli/lib/models/project.js:458:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/home/blieb/projects/akita/frontend/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/home/blieb/projects/akita/frontend/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/home/blieb/projects/akita/frontend/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/home/blieb/projects/akita/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/blieb/projects/akita/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/blieb/projects/akita/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/blieb/projects/akita/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)

{
  "name": "akita",
  "version": "0.1.0-SNAPSHOT",
  "description": "Front end for user namagement through NED",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "bower": "^1.3.12",
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-static-compiler": "0.2.1",
    "ember-cli": "0.2.1",
    "ember-cli-bootstrap-sass": "^0.2.11",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-document-title": "0.0.1",
    "ember-cli-esnext": "0.1.1",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-sass": "^3.1.0-beta.5",
    "ember-data": "git+https://github.com/emberjs/data#4c112b04bc14fa389cfa9c21420bec7e36c717da",
    "ember-data-factory-guy": "1.0.2",
    "ember-export-application-global": "^1.0.0",
    "ember-validations": "^2.0.0-alpha.3",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  },
  "dependencies": {
    "ember-cli-app-version": "^0.3.3"
  }
}

**Comment by danielspaniel** [comment]
Intersting .. I looked at that line in:
/home/blieb/projects/akita/frontend/node_modules/ember-cli/lib/models/project.js:459:53
 and it seems like it can not find the name of addon or the package name, which is odd. 

 can you remove ember-data-factory-guy from package.json
 then run> npm prune
 
then do the install again.

 ember install:addon ember-data-factory-guy

**Comment by danielspaniel** [comment]
Did you ever get this working?

**Comment by danielspaniel** [comment]
Last call before I close this?

**Comment by pixelterra** [comment]
Not really. Apparently the command in 0.2.3 should not have the ":addon" bit. Even after that, though the generator call failed.

**Comment by danielspaniel** [comment]
The generator error is a known [bug](https://github.com/ember-cli/ember-cli/issues/3831)
but on cli 0.2.3 factory guy still completes the install even with the generator name notice 
 I updated the docs to show the new command 
 ``` ember install ember-data-factory-guy ```
