### ISSUE TITLE
Install failure (ember-cli 0.2.1)

### ISSUE THREAD

**Issue by rtm** [danielspaniel/ember-data-factory-guy#87]
I get the following:

	[rtm@rtm-linux-vm ~/repo]$ ember install:addon ember-data-factory-guy
	The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/home/rtm/repo/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
	version: 0.2.1

	A new version of ember-cli is available (0.2.5). To install it, type ember update.
	Installed packages for tooling via npm.
	The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/home/rtm/repo/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
	Cannot read property 'name' of undefined
	TypeError: Cannot read property 'name' of undefined
	    at /home/rtm/repo/node_modules/ember-cli/lib/models/project.js:459:53
	    at find (/home/rtm/repo/node_modules/ember-cli/node_modules/lodash-node/modern/collections/find.js:64:11)
	    at Project.findAddonByName (/home/rtm/repo/node_modules/ember-cli/lib/models/project.js:458:20)
	    at Class.module.exports.Task.extend.findDefaultBlueprintName (/home/rtm/repo/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
	    at Class.module.exports.Task.extend.installBlueprint (/home/rtm/repo/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
	    at Class.<anonymous> (/home/rtm/repo/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
	    at lib$rsvp$$internal$$tryCatch (/home/rtm/repo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
	    at lib$rsvp$$internal$$invokeCallback (/home/rtm/repo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
	    at lib$rsvp$$internal$$publish (/home/rtm/repo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
	    at lib$rsvp$asap$$flush (/home/rtm/repo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
	[rtm@rtm-linux-vm ~/repo]$

Any clues or suggestions, other than upgrading to ember-cli 0.2.5 if that would make a difference?

**Comment by danielspaniel** [comment]
@rtm, good question, but there is not much you can do besides upgrade. Did factory-guy install anyway ( supposed to ) ... this error does not usually stop the install .. but just looks bad.

**Comment by rtm** [comment]
@danielspaniel Thanks, no it didn't install, the bower.json entries did not get made. I will try upgrading I guess.

**Comment by danielspaniel** [comment]
gulp, that is bummer. hopefully upgrade is not too painful ( it should not be too bad from 0.2.1 to o.2.5 ) .. but you can try 0.2.3 as well ( this error went away then )

**Comment by rtm** [comment]
OK, you can close this as it seems to be a known issue.
